version: '3'

services:
  redis-node-1:
    container_name: redis-node-1
    build:
      dockerfile: Dockerfile
      context: ./nodes/node-1
    networks:
      - redis-net

  redis-node-2:
    container_name: redis-node-2
    build:
      dockerfile: Dockerfile
      context: ./nodes/node-2
    networks:
      - redis-net
  
  redis-node-3:
    container_name: redis-node-3
    build:
      dockerfile: Dockerfile
      context: ./nodes/node-3
    networks:
      - redis-net

  redis-node-4:
    container_name: redis-node-4
    build:
      dockerfile: Dockerfile
      context: ./nodes/node-4
    networks:
      - redis-net

  redis-node-5:
    container_name: redis-node-5
    build:
      dockerfile: Dockerfile
      context: ./nodes/node-5
    networks:
      - redis-net

  redis-node-6:
    container_name: redis-node-6
    build:
      dockerfile: Dockerfile
      context: ./nodes/node-6
    networks:
      - redis-net

networks:
  redis-net:
